name: CI

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true
  
jobs:
  pages:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org/
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx parcel build examples/ --dist-dir .bin
      - uses: actions/configure-pages@v2.1.1
      - uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: .bin/
          retention-days: 7
      - uses: actions/deploy-pages@v1.2.2
